from oterminus.deterministic_shortcuts import (
    _build_match,
    _normalize_request,
    plan_with_deterministic_shortcut,
)
from oterminus.models import RiskLevel
from oterminus.policies import PolicyConfig
from oterminus.router import route_request
from oterminus.validator import ProposalOrigin, Validator


def _assert_local_arguments(request: str, command_family: str, arguments: dict) -> None:
    match = plan_with_deterministic_shortcut(request, route_request(request))
    assert match is not None, request
    assert match.proposal.command_family == command_family
    assert match.proposal.arguments == arguments
    assert match.proposal.mode == "structured"
    assert match.proposal.needs_confirmation is True


def test_deterministic_shortcut_normalizes_whitespace_and_case() -> None:
    assert _normalize_request("  Show   Current\nDirectory  ") == "show current directory"


def test_deterministic_shortcut_builder_returns_structured_proposal_with_rule_id() -> None:
    match = _build_match("demo_pwd", "pwd", {}, frozenset())

    assert match is not None
    assert match.rule_id == "demo_pwd"
    assert match.proposal.mode == "structured"
    assert match.proposal.command_family == "pwd"
    assert match.proposal.arguments == {}
    assert match.proposal.needs_confirmation is True
    assert "Generated by deterministic shortcut." in match.proposal.notes
    assert "demo_pwd" in match.proposal.explanation


def test_deterministic_shortcut_builder_respects_disabled_pack() -> None:
    assert _build_match("demo_pwd", "pwd", {}, frozenset({"filesystem"})) is None


def test_deterministic_shortcut_builder_respects_platform_availability() -> None:
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="linux") is None
    )
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="darwin")
        is not None
    )


def test_deterministic_shortcut_builder_fails_closed_on_invalid_structured_arguments() -> None:
    assert (
        _build_match("demo_git", "git", {"operation": "log_oneline", "count": 101}, frozenset())
        is None
    )


def test_deterministic_shortcut_maps_retained_zero_argument_shortcuts() -> None:
    cases = {
        "show current directory": ("pwd", {}),
        "where am i": ("pwd", {}),
        "print working directory": ("pwd", {}),
        "clear screen": ("clear", {}),
        "clear the screen": ("clear", {}),
    }

    for request, (command_family, arguments) in cases.items():
        _assert_local_arguments(request, command_family, arguments)


def test_deterministic_shortcut_respects_disabled_filesystem_pack_for_retained_shortcuts() -> None:
    disabled = frozenset({"filesystem"})
    match = plan_with_deterministic_shortcut(
        "show current directory",
        route_request("show current directory", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_deterministic_shortcut_removed_recipe_groups_fall_back_to_llm() -> None:
    removed_recipe_requests = (
        "show files",
        "show hidden files",
        "list files with sizes",
        "show disk usage for this folder",
        "show manual for ls",
        "show manual section 5 for crontab",
        "show first 20 lines of README.md",
        "show last 50 lines of app.log",
        "count lines in README.md",
        "search TODO in src",
        "show running processes",
        "find python processes",
        "show git status",
        "show current branch",
        "show last 5 commits",
        "run tests",
    )

    for request in removed_recipe_requests:
        assert plan_with_deterministic_shortcut(request, route_request(request)) is None, request


def test_deterministic_shortcut_unsafe_requests_fall_back() -> None:
    for request in ("delete junk", "install dependencies", "format the code"):
        assert plan_with_deterministic_shortcut(request, route_request(request)) is None, request


def test_deterministic_shortcut_validator_accepts_and_renders_retained_shortcuts() -> None:
    validator = Validator(PolicyConfig(mode=RiskLevel.WRITE, allow_dangerous=False))
    expected = {
        "show current directory": ("pwd", ["pwd"]),
        "clear screen": ("clear", ["clear"]),
    }

    for request, (rendered_command, argv) in expected.items():
        match = plan_with_deterministic_shortcut(request, route_request(request))
        assert match is not None

        validation = validator.validate(
            match.proposal, origin=ProposalOrigin.DETERMINISTIC_SHORTCUT
        )

        assert validation.accepted is True
        assert validation.risk_level == RiskLevel.SAFE
        assert validation.rendered_command == rendered_command
        assert validation.argv == argv
