from oterminus.local_planner import (
    _build_match,
    _extract_single_positive_integer,
    _has_unsafe_fragment,
    _normalize_request,
    _parse_local_path_token,
    _parse_manual_topic_token,
    _parse_positive_integer,
    _parse_search_term,
    plan_locally,
)
from oterminus.models import RiskLevel
from oterminus.policies import PolicyConfig
from oterminus.router import route_request
from oterminus.validator import ProposalOrigin, Validator


def _local_match(request: str):
    match = plan_locally(request, route_request(request))
    assert match is not None, request
    return match


def _assert_local_arguments(request: str, command_family: str, arguments: dict) -> None:
    match = _local_match(request)
    assert match.proposal.command_family == command_family
    assert match.proposal.arguments == arguments
    assert match.proposal.mode == "structured"
    assert match.proposal.needs_confirmation is True


def test_local_planner_normalizes_whitespace_and_case() -> None:
    assert _normalize_request("  Show   Current\nDirectory  ") == "show current directory"


def test_local_planner_rejects_unsafe_fragments() -> None:
    unsafe_values = (
        "README.md; whoami",
        "README.md && whoami",
        "README.md || whoami",
        "README.md | wc",
        "README.md > out",
        "README.md < in",
        "$(pwd)",
        "`pwd`",
        "README.md\x00",
        "README.md\nnext",
        "README.md\rnext",
    )

    for value in unsafe_values:
        assert _has_unsafe_fragment(value), value


def test_local_planner_parses_conservative_local_paths() -> None:
    for value in ("README.md", "src", "./docs", "docs/guide.md", "app.log", "."):
        assert _parse_local_path_token(value) == value


def test_local_planner_rejects_unsafe_local_paths() -> None:
    rejected = (
        "https://example.com",
        "-rf",
        "README.md && whoami",
        "$(pwd)",
        "`pwd`",
        "/",
        "~",
        "$HOME",
        "${HOME}",
        "/etc",
        "/tmp/file",
        "README*.md",
        "two words.txt",
    )

    for value in rejected:
        assert _parse_local_path_token(value) is None, value


def test_local_planner_parses_positive_integers() -> None:
    assert _parse_positive_integer("20") == 20
    assert _parse_positive_integer("1") == 1
    assert _parse_positive_integer("100", max_value=100) == 100


def test_local_planner_rejects_invalid_positive_integers() -> None:
    assert _parse_positive_integer("0") is None
    assert _parse_positive_integer("-1") is None
    assert _parse_positive_integer("1.5") is None
    assert _parse_positive_integer("101", max_value=100) is None
    assert _extract_single_positive_integer("first 20 lines and 5 files") is None


def test_local_planner_parses_conservative_manual_topics() -> None:
    for value in ("ls", "grep", "git", "gitignore", "ssh_config", "systemd-journald"):
        assert _parse_manual_topic_token(value) == value


def test_local_planner_rejects_unsafe_manual_topics() -> None:
    rejected = (
        "",
        "-P",
        "https://example.com",
        "./script.sh",
        "/bin/ls",
        "docs/file.md",
        "ls;whoami",
        "$(whoami)",
        "`whoami`",
        "two words",
        "README*.md",
        ".hidden",
        "~user",
    )

    for value in rejected:
        assert _parse_manual_topic_token(value) is None, value


def test_local_planner_parses_simple_search_terms() -> None:
    assert _parse_search_term("TODO") == "TODO"
    assert _parse_search_term('"TODO"') == "TODO"
    assert _parse_search_term("'todo'") == "todo"
    assert _parse_search_term("error") == "error"


def test_local_planner_rejects_unsafe_search_terms() -> None:
    rejected = ("", "TODO && whoami", "$(pwd)", "`pwd`", "two words", "-n", "TODO\nnext")

    for value in rejected:
        assert _parse_search_term(value) is None, value


def test_local_planner_builder_returns_structured_proposal_with_rule_id() -> None:
    match = _build_match("demo_pwd", "pwd", {}, frozenset())

    assert match is not None
    assert match.rule_id == "demo_pwd"
    assert match.proposal.mode == "structured"
    assert match.proposal.command_family == "pwd"
    assert match.proposal.arguments == {}
    assert match.proposal.needs_confirmation is True
    assert "Generated by deterministic shortcut." in match.proposal.notes
    assert "demo_pwd" in match.proposal.explanation


def test_local_planner_builder_respects_disabled_pack() -> None:
    assert (
        _build_match("demo_git", "git", {"operation": "status_short"}, frozenset({"git"})) is None
    )


def test_local_planner_builder_respects_platform_availability() -> None:
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="linux") is None
    )
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="darwin")
        is not None
    )


def test_local_planner_builder_fails_closed_on_invalid_structured_arguments() -> None:
    assert (
        _build_match("demo_git", "git", {"operation": "log_oneline", "count": 101}, frozenset())
        is None
    )


def test_local_planner_maps_current_directory() -> None:
    match = plan_locally("show current directory", route_request("show current directory"))
    assert match is not None
    assert match.proposal.command_family == "pwd"


def test_local_planner_maps_files_with_sizes() -> None:
    match = plan_locally("list files with sizes", route_request("list files with sizes"))
    assert match is not None
    assert match.proposal.command_family == "ls"
    assert match.proposal.arguments == {
        "path": ".",
        "long": True,
        "human_readable": True,
        "all": False,
        "recursive": False,
    }


def test_local_planner_maps_filesystem_inspection_recipes() -> None:
    cases = {
        "show hidden files": (
            "ls",
            {
                "path": ".",
                "long": False,
                "human_readable": False,
                "all": True,
                "recursive": False,
            },
        ),
        "show all files": (
            "ls",
            {
                "path": ".",
                "long": False,
                "human_readable": False,
                "all": True,
                "recursive": False,
            },
        ),
        "show detailed files": (
            "ls",
            {
                "path": ".",
                "long": True,
                "human_readable": True,
                "all": False,
                "recursive": False,
            },
        ),
        "show file info for README.md": (
            "stat",
            {"path": "README.md", "dereference": False, "verbose": False},
        ),
        "show metadata for README.md": (
            "stat",
            {"path": "README.md", "dereference": False, "verbose": False},
        ),
        "identify README.md": ("file", {"paths": ["README.md"], "brief": False}),
        "identify file README.md": ("file", {"paths": ["README.md"], "brief": False}),
    }

    for request, (command_family, arguments) in cases.items():
        _assert_local_arguments(request, command_family, arguments)


def test_local_planner_disabled_filesystem_pack_blocks_filesystem_recipes() -> None:
    disabled = frozenset({"filesystem"})

    for request in (
        "show hidden files",
        "show detailed files",
        "show file info for README.md",
        "identify README.md",
    ):
        match = plan_locally(
            request,
            route_request(request, disabled_pack_ids=disabled),
            disabled_pack_ids=disabled,
        )
        assert match is None, request


def test_local_planner_maps_disk_usage_folder() -> None:
    match = plan_locally(
        "show disk usage for this folder", route_request("show disk usage for this folder")
    )
    assert match is not None
    assert match.proposal.command_family == "du"


def test_local_planner_maps_manual_page_recipes() -> None:
    cases = {
        "show manual for ls": ("man", {"topic": "ls", "section": None}),
        "show me the manual of ls": ("man", {"topic": "ls", "section": None}),
        "sho me the manual page for ls": ("man", {"topic": "ls", "section": None}),
        "show me the manual page for a command called ls": (
            "man",
            {"topic": "ls", "section": None},
        ),
        "show man page for grep": ("man", {"topic": "grep", "section": None}),
        "show the man page for grep": ("man", {"topic": "grep", "section": None}),
        "open man page for tar": ("man", {"topic": "tar", "section": None}),
        "manual page for git": ("man", {"topic": "git", "section": None}),
        "what is the manual for git": ("man", {"topic": "git", "section": None}),
        "show manual section 5 for crontab": ("man", {"topic": "crontab", "section": "5"}),
        "show man page for crontab section 5": (
            "man",
            {"topic": "crontab", "section": "5"},
        ),
    }

    for request, (command_family, arguments) in cases.items():
        _assert_local_arguments(request, command_family, arguments)


def test_local_planner_manual_page_recipes_fail_closed() -> None:
    requests = (
        "help me with ls",
        "how do I list files",
        "explain grep",
        "what flags should I use for tar",
        "how do I use chmod",
        "teach me grep",
        "show manual for https://example.com",
        "show manual for ./script.sh",
        "show manual for /bin/ls",
        "show manual for docs/file.md",
        "show manual for ls; whoami",
        "show manual for $(whoami)",
        "show manual section abc for ls",
        "show manual section 99 for ls",
        "show manual -P cat for ls",
    )

    for request in requests:
        assert plan_locally(request, route_request(request)) is None, request


def test_local_planner_disabled_system_pack_blocks_manual_page_recipes() -> None:
    disabled = frozenset({"system"})
    match = plan_locally(
        "show manual for ls",
        route_request("show manual for ls", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_local_planner_maps_text_inspection_recipes() -> None:
    grep_src_arguments = {
        "pattern": "TODO",
        "paths": ["src"],
        "ignore_case": False,
        "line_number": True,
        "fixed_strings": True,
        "recursive": True,
        "files_with_matches": False,
        "max_count": None,
    }
    cases = {
        "show README.md": ("cat", {"paths": ["README.md"]}),
        "show file README.md": ("cat", {"paths": ["README.md"]}),
        "print README.md": ("cat", {"paths": ["README.md"]}),
        "show first 20 lines of README.md": (
            "head",
            {"paths": ["README.md"], "lines": 20, "bytes": None},
        ),
        "show last 50 lines of app.log": (
            "tail",
            {"paths": ["app.log"], "lines": 50, "bytes": None},
        ),
        "count lines in README.md": (
            "wc",
            {"paths": ["README.md"], "lines": True, "words": False, "bytes": False},
        ),
        "count words in README.md": (
            "wc",
            {"paths": ["README.md"], "lines": False, "words": True, "bytes": False},
        ),
        "search TODO in src": ("grep", grep_src_arguments),
        'search "TODO" in src': ("grep", grep_src_arguments),
        "find TODO in README.md": (
            "grep",
            {
                "pattern": "TODO",
                "paths": ["README.md"],
                "ignore_case": False,
                "line_number": True,
                "fixed_strings": True,
                "recursive": False,
                "files_with_matches": False,
                "max_count": None,
            },
        ),
    }

    for request, (command_family, arguments) in cases.items():
        _assert_local_arguments(request, command_family, arguments)


def test_local_planner_disabled_text_pack_blocks_text_recipes() -> None:
    disabled = frozenset({"text"})

    for request in (
        "show README.md",
        "show first 20 lines of README.md",
        "show last 50 lines of app.log",
        "count lines in README.md",
        "search TODO in src",
    ):
        match = plan_locally(
            request,
            route_request(request, disabled_pack_ids=disabled),
            disabled_pack_ids=disabled,
        )
        assert match is None, request


def test_local_planner_maps_process_inspection_recipes() -> None:
    for request in ("show running processes", "show all processes", "show processes"):
        _assert_local_arguments(
            request,
            "ps",
            {"all_processes": True, "full_format": False, "user": None, "pid": None},
        )

    for request in (
        "find python processes",
        "find process python",
        "find processes matching python",
    ):
        _assert_local_arguments(
            request,
            "pgrep",
            {"pattern": "python", "full_command": True, "list_names": True, "user": None},
        )


def test_local_planner_disabled_process_pack_blocks_process_recipes() -> None:
    disabled = frozenset({"process"})

    for request in ("show running processes", "find python processes"):
        match = plan_locally(
            request,
            route_request(request, disabled_pack_ids=disabled),
            disabled_pack_ids=disabled,
        )
        assert match is None, request


def test_local_planner_respects_disabled_git_pack() -> None:
    match = plan_locally(
        "show git status",
        route_request("show git status"),
        disabled_pack_ids=frozenset({"git"}),
    )
    assert match is None


def test_local_planner_maps_git_inspection_recipes() -> None:
    cases = {
        "show current branch": ("git", {"operation": "branch_current", "count": 10}),
        "show current git branch": ("git", {"operation": "branch_current", "count": 10}),
        "what branch am i on": ("git", {"operation": "branch_current", "count": 10}),
        "show recent commits": ("git", {"operation": "log_oneline", "count": 10}),
        "show last 5 commits": ("git", {"operation": "log_oneline", "count": 5}),
        "show changed files": ("git", {"operation": "diff_name_only", "count": 10}),
        "show git diff summary": ("git", {"operation": "diff_stat", "count": 10}),
    }

    for request, (command_family, arguments) in cases.items():
        _assert_local_arguments(request, command_family, arguments)


def test_local_planner_respects_beginner_profile_disabled_packs() -> None:
    disabled = frozenset({"archive", "dangerous", "git", "macos", "network", "process", "project"})

    match = plan_locally(
        "show git status",
        route_request("show git status", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_local_planner_maps_project_health_requests() -> None:
    cases = {
        "run tests": "run_tests",
        "run the test suite": "run_tests",
        "check linting": "lint_check",
        "run ruff check": "lint_check",
        "check formatting": "format_check",
        "run format check": "format_check",
        "build docs": "build_docs",
        "check docs build": "build_docs",
        "run evals": "run_evals",
    }

    for request, operation in cases.items():
        match = plan_locally(request, route_request(request))
        assert match is not None, request
        assert match.proposal.command_family == "project_health"
        assert match.proposal.arguments == {"operation": operation}
        assert match.proposal.needs_confirmation is True


def test_local_planner_respects_disabled_project_pack() -> None:
    disabled = frozenset({"project"})
    match = plan_locally(
        "run tests",
        route_request("run tests", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_local_planner_unsafe_requests_fall_back() -> None:
    assert plan_locally("delete junk", route_request("delete junk")) is None
    assert plan_locally("install dependencies", route_request("install dependencies")) is None
    assert plan_locally("format the code", route_request("format the code")) is None


def test_local_planner_recipe_unsafe_requests_fall_back() -> None:
    requests = (
        "show first 20 lines of README.md && whoami",
        "search TODO in src | cat",
        "count lines in https://example.com",
        "show / files",
        "find -rf processes",
        "show last -5 lines of app.log",
        "show first 0 lines of README.md",
        "delete README.md",
        "move README.md to backup",
        "git reset hard",
        "git clean everything",
    )

    for request in requests:
        assert plan_locally(request, route_request(request)) is None, request


def test_local_planner_validator_accepts_and_renders_new_structured_recipes() -> None:
    validator = Validator(PolicyConfig(mode=RiskLevel.WRITE, allow_dangerous=False))
    expected = {
        "show first 20 lines of README.md": (
            "head -n 20 README.md",
            ["head", "-n", "20", "README.md"],
        ),
        "search TODO in src": (
            "grep -F -n -r TODO src",
            ["grep", "-F", "-n", "-r", "TODO", "src"],
        ),
        "show last 5 commits": (
            "git log --oneline -n 5",
            ["git", "log", "--oneline", "-n", "5"],
        ),
        "find python processes": ("pgrep -f -l python", ["pgrep", "-f", "-l", "python"]),
        "identify README.md": ("file README.md", ["file", "README.md"]),
        "show manual for ls": ("man ls", ["man", "ls"]),
        "show manual section 5 for crontab": (
            "man 5 crontab",
            ["man", "5", "crontab"],
        ),
    }

    for request, (rendered_command, argv) in expected.items():
        match = _local_match(request)
        validation = validator.validate(
            match.proposal, origin=ProposalOrigin.DETERMINISTIC_SHORTCUT
        )

        assert validation.accepted is True
        assert validation.risk_level == RiskLevel.SAFE
        assert validation.rendered_command == rendered_command
        assert validation.argv == argv
