from oterminus.local_planner import (
    _build_match,
    _extract_single_positive_integer,
    _has_unsafe_fragment,
    _normalize_request,
    _parse_local_path_token,
    _parse_positive_integer,
    _parse_search_term,
    plan_locally,
)
from oterminus.router import route_request


def test_local_planner_normalizes_whitespace_and_case() -> None:
    assert _normalize_request("  Show   Current\nDirectory  ") == "show current directory"


def test_local_planner_rejects_unsafe_fragments() -> None:
    unsafe_values = (
        "README.md; whoami",
        "README.md && whoami",
        "README.md || whoami",
        "README.md | wc",
        "README.md > out",
        "README.md < in",
        "$(pwd)",
        "`pwd`",
        "README.md\x00",
        "README.md\nnext",
        "README.md\rnext",
    )

    for value in unsafe_values:
        assert _has_unsafe_fragment(value), value


def test_local_planner_parses_conservative_local_paths() -> None:
    for value in ("README.md", "src", "./docs", "docs/guide.md", "app.log", "."):
        assert _parse_local_path_token(value) == value


def test_local_planner_rejects_unsafe_local_paths() -> None:
    rejected = (
        "https://example.com",
        "-rf",
        "README.md && whoami",
        "$(pwd)",
        "`pwd`",
        "/",
        "~",
        "$HOME",
        "${HOME}",
        "/etc",
        "/tmp/file",
        "README*.md",
        "two words.txt",
    )

    for value in rejected:
        assert _parse_local_path_token(value) is None, value


def test_local_planner_parses_positive_integers() -> None:
    assert _parse_positive_integer("20") == 20
    assert _parse_positive_integer("1") == 1
    assert _parse_positive_integer("100", max_value=100) == 100


def test_local_planner_rejects_invalid_positive_integers() -> None:
    assert _parse_positive_integer("0") is None
    assert _parse_positive_integer("-1") is None
    assert _parse_positive_integer("1.5") is None
    assert _parse_positive_integer("101", max_value=100) is None
    assert _extract_single_positive_integer("first 20 lines and 5 files") is None


def test_local_planner_parses_simple_search_terms() -> None:
    assert _parse_search_term("TODO") == "TODO"
    assert _parse_search_term('"TODO"') == "TODO"
    assert _parse_search_term("'todo'") == "todo"
    assert _parse_search_term("error") == "error"


def test_local_planner_rejects_unsafe_search_terms() -> None:
    rejected = ("", "TODO && whoami", "$(pwd)", "`pwd`", "two words", "-n", "TODO\nnext")

    for value in rejected:
        assert _parse_search_term(value) is None, value


def test_local_planner_builder_returns_structured_proposal_with_rule_id() -> None:
    match = _build_match("demo_pwd", "pwd", {}, frozenset())

    assert match is not None
    assert match.rule_id == "demo_pwd"
    assert match.proposal.mode == "structured"
    assert match.proposal.command_family == "pwd"
    assert match.proposal.arguments == {}
    assert match.proposal.needs_confirmation is True
    assert "Generated by deterministic local planner." in match.proposal.notes
    assert "demo_pwd" in match.proposal.explanation


def test_local_planner_builder_respects_disabled_pack() -> None:
    assert (
        _build_match("demo_git", "git", {"operation": "status_short"}, frozenset({"git"})) is None
    )


def test_local_planner_builder_respects_platform_availability() -> None:
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="linux") is None
    )
    assert (
        _build_match("demo_open", "open", {"path": "."}, frozenset(), platform_id="darwin")
        is not None
    )


def test_local_planner_builder_fails_closed_on_invalid_structured_arguments() -> None:
    assert (
        _build_match("demo_git", "git", {"operation": "log_oneline", "count": 101}, frozenset())
        is None
    )


def test_local_planner_maps_current_directory() -> None:
    match = plan_locally("show current directory", route_request("show current directory"))
    assert match is not None
    assert match.proposal.command_family == "pwd"


def test_local_planner_maps_files_with_sizes() -> None:
    match = plan_locally("list files with sizes", route_request("list files with sizes"))
    assert match is not None
    assert match.proposal.command_family == "ls"
    assert match.proposal.arguments == {
        "path": ".",
        "long": True,
        "human_readable": True,
        "all": False,
        "recursive": False,
    }


def test_local_planner_maps_disk_usage_folder() -> None:
    match = plan_locally(
        "show disk usage for this folder", route_request("show disk usage for this folder")
    )
    assert match is not None
    assert match.proposal.command_family == "du"


def test_local_planner_respects_disabled_git_pack() -> None:
    match = plan_locally(
        "show git status",
        route_request("show git status"),
        disabled_pack_ids=frozenset({"git"}),
    )
    assert match is None


def test_local_planner_respects_beginner_profile_disabled_packs() -> None:
    disabled = frozenset({"archive", "dangerous", "git", "macos", "network", "process", "project"})

    match = plan_locally(
        "show git status",
        route_request("show git status", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_local_planner_maps_project_health_requests() -> None:
    cases = {
        "run tests": "run_tests",
        "run the test suite": "run_tests",
        "check linting": "lint_check",
        "run ruff check": "lint_check",
        "check formatting": "format_check",
        "run format check": "format_check",
        "build docs": "build_docs",
        "check docs build": "build_docs",
        "run evals": "run_evals",
    }

    for request, operation in cases.items():
        match = plan_locally(request, route_request(request))
        assert match is not None, request
        assert match.proposal.command_family == "project_health"
        assert match.proposal.arguments == {"operation": operation}
        assert match.proposal.needs_confirmation is True


def test_local_planner_respects_disabled_project_pack() -> None:
    disabled = frozenset({"project"})
    match = plan_locally(
        "run tests",
        route_request("run tests", disabled_pack_ids=disabled),
        disabled_pack_ids=disabled,
    )

    assert match is None


def test_local_planner_unsafe_requests_fall_back() -> None:
    assert plan_locally("delete junk", route_request("delete junk")) is None
    assert plan_locally("install dependencies", route_request("install dependencies")) is None
    assert plan_locally("format the code", route_request("format the code")) is None
