from oterminus.models import RiskLevel

from .types import CommandSpec, DirectDetectionMode, PathOperandMode, command

FILESYSTEM_INSPECTION = {
    "capability_id": "filesystem_inspection",
    "capability_label": "Filesystem inspection",
    "capability_description": "Inspect local files, folders, and metadata safely.",
}
FILESYSTEM_MUTATION = {
    "capability_id": "filesystem_mutation",
    "capability_label": "Filesystem mutation",
    "capability_description": "Create, copy, move, or modify files and directory state.",
}

COMMAND_PACK: tuple[CommandSpec, ...] = (
    command(
        name="cd",
        category="navigation",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        direct_detection_mode=DirectDetectionMode.CD,
        path_operand_mode=PathOperandMode.CD,
        examples=("cd src",),
        natural_language_aliases=("change directory", "go to folder"),
        notes=("Changes the oterminus working directory for the current REPL session.",),
    ),
    command(
        name="ls",
        category="inspection",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        allowed_flags=("-a", "-h", "-l", "-R"),
        examples=("ls -la",),
        natural_language_aliases=("list files", "show directory contents"),
    ),
    command(
        name="pwd",
        category="navigation",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        direct_detection_mode=DirectDetectionMode.ZERO_OPERANDS,
        examples=("pwd",),
        natural_language_aliases=("where am i", "print working directory"),
    ),
    command(
        name="find",
        category="search",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        direct_detection_mode=DirectDetectionMode.FIND,
        path_operand_mode=PathOperandMode.FIND,
        leading_flags=("-H", "-L", "-P"),
        leading_flags_with_values=("-D", "-O"),
        leading_flags_with_inline_values=("-O",),
        allowed_flags=("-name", "-path", "-type", "-maxdepth", "-mindepth", "-print"),
        examples=("find . -name '*.py'",),
        natural_language_aliases=("find files", "search directories"),
    ),
    command(
        name="du",
        category="inspection",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        allowed_flags=("-a", "-c", "-h", "-k", "-s", "-x"),
        flags_with_values=("-d",),
        examples=("du -h .",),
        natural_language_aliases=("disk usage", "folder size"),
    ),
    command(
        name="stat",
        category="inspection",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        min_operands=1,
        allowed_flags=("-L", "-x"),
        flags_with_values=("-f",),
        examples=("stat README.md",),
        natural_language_aliases=("file metadata", "file info"),
    ),
    command(
        name="mkdir",
        category="filesystem_write",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.WRITE,
        min_operands=1,
        allowed_flags=("-p",),
        examples=("mkdir -p logs/archive",),
        natural_language_aliases=("create folder", "make directory"),
    ),
    command(
        name="cp",
        category="filesystem_write",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.WRITE,
        min_operands=2,
        allowed_flags=("-R", "-n", "-p"),
        examples=("cp notes.txt backup/notes.txt",),
        natural_language_aliases=("copy file", "duplicate file"),
    ),
    command(
        name="mv",
        category="filesystem_write",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.WRITE,
        min_operands=2,
        allowed_flags=("-n",),
        examples=("mv report.md docs/",),
        natural_language_aliases=("move file", "rename file"),
    ),
    command(
        name="chmod",
        category="permissions",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.WRITE,
        min_operands=2,
        flags_with_values=("--context", "--reference"),
        path_valued_flags=("--reference",),
        dangerous_target_literals=("/", "/*"),
        examples=("chmod 755 script.sh",),
        natural_language_aliases=("change permissions", "set file mode"),
    ),
    command(
        name="touch",
        category="filesystem_write",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.WRITE,
        min_operands=1,
        examples=("touch notes.txt",),
        natural_language_aliases=("create empty file",),
    ),
    command(
        name="chown",
        category="permissions",
        **FILESYSTEM_MUTATION,
        risk_level=RiskLevel.DANGEROUS,
        min_operands=2,
        dangerous_target_literals=("/", "/*"),
        examples=("chown user:group file.txt",),
        natural_language_aliases=("change file owner",),
    ),
    command(
        name="file",
        category="inspection",
        **FILESYSTEM_INSPECTION,
        risk_level=RiskLevel.SAFE,
        min_operands=1,
        allowed_flags=("-b",),
        examples=("file README.md",),
        natural_language_aliases=("identify file type",),
    ),
)
