from __future__ import annotations

from dataclasses import dataclass
import re

from oterminus.commands import get_enabled_command_spec
from oterminus.models import Proposal, ProposalMode
from oterminus.router import RouteResult


@dataclass(frozen=True, slots=True)
class DeterministicShortcutMatch:
    proposal: Proposal
    rule_id: str


def plan_with_deterministic_shortcut(
    request: str,
    route: RouteResult | None,
    *,
    disabled_pack_ids: frozenset[str] = frozenset(),
    platform_id: str | None = None,
) -> DeterministicShortcutMatch | None:
    """Return a governed deterministic shortcut match, if one exists.

    This layer is intentionally tiny. Flexible natural language belongs to the
    LLM planner; do not add phrase variants or argument-extracting recipes here.
    """
    _ = route
    text = _normalize_request(request)
    if not text:
        return None

    if text in {"show current directory", "where am i", "print working directory"}:
        return _build_match(
            "show_current_directory", "pwd", {}, disabled_pack_ids, platform_id=platform_id
        )

    if text in {"clear screen", "clear the screen"}:
        return _build_match("clear_screen", "clear", {}, disabled_pack_ids, platform_id=platform_id)

    return None


def _normalize_request(request: str) -> str:
    lowered = request.strip().lower()
    return re.sub(r"\s+", " ", lowered)


def _build_match(
    rule_id: str,
    command_family: str,
    arguments: dict,
    disabled_pack_ids: frozenset[str],
    *,
    platform_id: str | None = None,
) -> DeterministicShortcutMatch | None:
    if (
        get_enabled_command_spec(
            command_family,
            disabled_pack_ids=disabled_pack_ids,
            platform_id=platform_id,
        )
        is None
    ):
        return None
    try:
        proposal = Proposal.model_validate(
            {
                "summary": "Execute a deterministic structured command.",
                "explanation": f"Matched deterministic shortcut rule: {rule_id}.",
                "mode": ProposalMode.STRUCTURED.value,
                "command_family": command_family,
                "arguments": arguments,
                "needs_confirmation": True,
                "notes": ["Generated by deterministic shortcut."],
            }
        )
    except ValueError:
        return None
    return DeterministicShortcutMatch(proposal=proposal, rule_id=rule_id)
