from __future__ import annotations

from dataclasses import dataclass
import re
from pathlib import Path

from oterminus.commands import get_enabled_command_spec
from oterminus.models import Proposal, ProposalMode
from oterminus.router import RouteResult

_UNSAFE_FRAGMENTS = (";", "&&", "||", "|", ">", "<", "$(", "`", "\x00", "\n", "\r")
_WILDCARD_FRAGMENTS = ("*", "?", "[", "]", "{", "}")
_BROAD_ROOTS = {
    "/",
    "~",
    "$HOME",
    "${HOME}",
    "/bin",
    "/dev",
    "/etc",
    "/home",
    "/lib",
    "/private",
    "/root",
    "/sbin",
    "/Users",
    "/usr",
    "/var",
}
_LOCAL_PATH_RE = re.compile(r"^[A-Za-z0-9._@%+=:,/.-]+$")
_INTEGER_RE = re.compile(r"^[1-9][0-9]*$")


@dataclass(frozen=True, slots=True)
class LocalPlannerMatch:
    proposal: Proposal
    rule_id: str


def plan_locally(
    request: str,
    route: RouteResult | None,
    *,
    disabled_pack_ids: frozenset[str] = frozenset(),
    platform_id: str | None = None,
) -> LocalPlannerMatch | None:
    text = _normalize_request(request)
    if not text:
        return None

    if text in {"show current directory", "where am i", "print working directory"}:
        return _build_match(
            "show_current_directory", "pwd", {}, disabled_pack_ids, platform_id=platform_id
        )

    if text in {"clear screen", "clear the screen"}:
        return _build_match("clear_screen", "clear", {}, disabled_pack_ids, platform_id=platform_id)

    if text in {"show files", "list files", "show files here"}:
        return _build_match(
            "show_files",
            "ls",
            {"path": ".", "long": False, "human_readable": False},
            disabled_pack_ids,
            platform_id=platform_id,
        )

    if text in {"show files with details", "list files with sizes"}:
        return _build_match(
            "show_files_detailed",
            "ls",
            {"path": ".", "long": True, "human_readable": True},
            disabled_pack_ids,
            platform_id=platform_id,
        )

    if (
        route
        and route.category == "metadata_inspect"
        and text
        in {
            "show disk usage",
            "show disk usage for this folder",
        }
    ):
        if text.endswith("for this folder"):
            return _build_match(
                "disk_usage_folder",
                "du",
                {"path": ".", "summarize": True, "human_readable": True},
                disabled_pack_ids,
                platform_id=platform_id,
            )
        return _build_match(
            "disk_usage",
            "df",
            {"human_readable": True},
            disabled_pack_ids,
            platform_id=platform_id,
        )

    if (
        route
        and route.category == "git_inspection"
        and text
        in {
            "show git status",
            "show short git status",
        }
    ):
        return _build_match(
            "git_status",
            "git",
            {"operation": "status_short"},
            disabled_pack_ids,
            platform_id=platform_id,
        )

    if route and route.category == "project_health":
        operation = _project_health_operation(text)
        if operation is not None:
            return _build_match(
                f"project_health_{operation}",
                "project_health",
                {"operation": operation},
                disabled_pack_ids,
                platform_id=platform_id,
            )

    return None


def _normalize_request(request: str) -> str:
    lowered = request.strip().lower()
    return re.sub(r"\s+", " ", lowered)


def _build_match(
    rule_id: str,
    command_family: str,
    arguments: dict,
    disabled_pack_ids: frozenset[str],
    *,
    platform_id: str | None = None,
) -> LocalPlannerMatch | None:
    if (
        get_enabled_command_spec(
            command_family,
            disabled_pack_ids=disabled_pack_ids,
            platform_id=platform_id,
        )
        is None
    ):
        return None
    try:
        proposal = Proposal.model_validate(
            {
                "summary": "Execute a deterministic structured command.",
                "explanation": f"Matched deterministic local planner rule: {rule_id}.",
                "mode": ProposalMode.STRUCTURED.value,
                "command_family": command_family,
                "arguments": arguments,
                "needs_confirmation": True,
                "notes": ["Generated by deterministic local planner."],
            }
        )
    except ValueError:
        return None
    return LocalPlannerMatch(proposal=proposal, rule_id=rule_id)


def _has_unsafe_fragment(value: str) -> bool:
    return any(fragment in value for fragment in _UNSAFE_FRAGMENTS)


def _has_wildcard_fragment(value: str) -> bool:
    return any(fragment in value for fragment in _WILDCARD_FRAGMENTS)


def _looks_like_url(value: str) -> bool:
    lowered = value.lower()
    return "://" in lowered or lowered.startswith(("mailto:", "file:"))


def _parse_local_path_token(value: str) -> str | None:
    path = _strip_simple_quotes(value.strip())
    if path is None:
        return None
    if not path or path.startswith("-"):
        return None
    if _has_unsafe_fragment(path) or _has_wildcard_fragment(path) or _looks_like_url(path):
        return None
    if any(char.isspace() for char in path):
        return None
    if path in _BROAD_ROOTS:
        return None
    if path.rstrip("/") in _BROAD_ROOTS:
        return None
    if path.startswith(("~/", "$HOME/", "${HOME}/")):
        return None
    if Path(path).is_absolute():
        return None
    if not _LOCAL_PATH_RE.fullmatch(path):
        return None
    return path


def _parse_positive_integer(value: str, *, max_value: int | None = None) -> int | None:
    stripped = value.strip()
    if not _INTEGER_RE.fullmatch(stripped):
        return None
    parsed = int(stripped, 10)
    if max_value is not None and parsed > max_value:
        return None
    return parsed


def _extract_single_positive_integer(text: str, *, max_value: int | None = None) -> int | None:
    numbers = re.findall(r"(?<![\w.-])\d+(?![\w.-])", text)
    if len(numbers) != 1:
        return None
    return _parse_positive_integer(numbers[0], max_value=max_value)


def _parse_search_term(value: str) -> str | None:
    term = _strip_simple_quotes(value.strip())
    if term is None:
        return None
    if not term or term.startswith("-"):
        return None
    if _has_unsafe_fragment(term) or _has_wildcard_fragment(term):
        return None
    if any(char.isspace() for char in term):
        return None
    if "'" in term or '"' in term:
        return None
    return term


def _strip_simple_quotes(value: str) -> str | None:
    if len(value) < 2:
        return value
    first = value[0]
    last = value[-1]
    if first not in {"'", '"'} and last not in {"'", '"'}:
        return value
    if first != last or first not in {"'", '"'}:
        return None
    inner = value[1:-1]
    if first in inner:
        return None
    return inner


def _project_health_operation(text: str) -> str | None:
    if text in {"run tests", "run the test suite", "run project tests"}:
        return "run_tests"
    if text in {"check linting", "run ruff check", "check ruff", "run project lint"}:
        return "lint_check"
    if text in {
        "check formatting",
        "check if formatting is okay",
        "run format check",
        "check project formatting",
    }:
        return "format_check"
    if text in {"build docs", "check docs build", "run mkdocs build", "build project docs"}:
        return "build_docs"
    if text in {"run evals", "run oterminus evals", "run project evals"}:
        return "run_evals"
    return None
