from __future__ import annotations

from dataclasses import dataclass
import re

from oterminus.commands import get_enabled_command_spec
from oterminus.models import Proposal, ProposalMode
from oterminus.router import RouteResult


@dataclass(frozen=True, slots=True)
class LocalPlannerMatch:
    proposal: Proposal
    rule_id: str


def plan_locally(
    request: str,
    route: RouteResult | None,
    *,
    disabled_pack_ids: frozenset[str] = frozenset(),
) -> LocalPlannerMatch | None:
    text = _normalize_request(request)
    if not text:
        return None

    if text in {"show current directory", "where am i", "print working directory"}:
        return _build_match("show_current_directory", "pwd", {}, disabled_pack_ids)

    if text in {"clear screen", "clear the screen"}:
        return _build_match("clear_screen", "clear", {}, disabled_pack_ids)

    if text in {"show files", "list files", "show files here"}:
        return _build_match(
            "show_files",
            "ls",
            {"path": ".", "long": False, "human_readable": False},
            disabled_pack_ids,
        )

    if text in {"show files with details", "list files with sizes"}:
        return _build_match(
            "show_files_detailed",
            "ls",
            {"path": ".", "long": True, "human_readable": True},
            disabled_pack_ids,
        )

    if (
        route
        and route.category == "metadata_inspect"
        and text
        in {
            "show disk usage",
            "show disk usage for this folder",
        }
    ):
        if text.endswith("for this folder"):
            return _build_match(
                "disk_usage_folder",
                "du",
                {"path": ".", "summarize": True, "human_readable": True},
                disabled_pack_ids,
            )
        return _build_match("disk_usage", "df", {"human_readable": True}, disabled_pack_ids)

    if (
        route
        and route.category == "git_inspection"
        and text
        in {
            "show git status",
            "show short git status",
        }
    ):
        return _build_match("git_status", "git", {"operation": "status_short"}, disabled_pack_ids)

    if route and route.category == "project_health":
        operation = _project_health_operation(text)
        if operation is not None:
            return _build_match(
                f"project_health_{operation}",
                "project_health",
                {"operation": operation},
                disabled_pack_ids,
            )

    return None


def _normalize_request(request: str) -> str:
    lowered = request.strip().lower()
    return re.sub(r"\s+", " ", lowered)


def _build_match(
    rule_id: str, command_family: str, arguments: dict, disabled_pack_ids: frozenset[str]
) -> LocalPlannerMatch | None:
    if get_enabled_command_spec(command_family, disabled_pack_ids=disabled_pack_ids) is None:
        return None
    proposal = Proposal.model_validate(
        {
            "summary": "Execute a deterministic structured command.",
            "explanation": f"Matched deterministic local planner rule: {rule_id}.",
            "mode": ProposalMode.STRUCTURED.value,
            "command_family": command_family,
            "arguments": arguments,
            "needs_confirmation": True,
            "notes": ["Generated by deterministic local planner."],
        }
    )
    return LocalPlannerMatch(proposal=proposal, rule_id=rule_id)


def _project_health_operation(text: str) -> str | None:
    if text in {"run tests", "run the test suite", "run project tests"}:
        return "run_tests"
    if text in {"check linting", "run ruff check", "check ruff", "run project lint"}:
        return "lint_check"
    if text in {
        "check formatting",
        "check if formatting is okay",
        "run format check",
        "check project formatting",
    }:
        return "format_check"
    if text in {"build docs", "check docs build", "run mkdocs build", "build project docs"}:
        return "build_docs"
    if text in {"run evals", "run oterminus evals", "run project evals"}:
        return "run_evals"
    return None
